# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: running_ads
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_for_running_adv_api
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8888:80"
    depends_on:
      - db
      
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP (アプリはここに送る)
      - "8025:8025" # Web UI (http://localhost:8025)
    restart: unless-stopped
    # 同じcompose内の他サービスからはホスト名 "mailhog" で到達可
      
volumes:
  pgdata: {}
  